/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avrwb_comm_impl_AwbSerialPort */

#ifndef _Included_com_avrwb_comm_impl_AwbSerialPort
#define _Included_com_avrwb_comm_impl_AwbSerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avrwb_comm_impl_AwbSerialPort
 * Method:    nativeOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_avrwb_comm_impl_AwbSerialPort_nativeOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_avrwb_comm_impl_AwbSerialPort
 * Method:    setSerialPortParams
 * Signature: (ILcom/avrwb/comm/DataBits;Lcom/avrwb/comm/StopBits;Lcom/avrwb/comm/Parity;)V
 */
JNIEXPORT void JNICALL Java_com_avrwb_comm_impl_AwbSerialPort_setSerialPortParams
  (JNIEnv *, jobject, jint, jobject, jobject, jobject);

/*
 * Class:     com_avrwb_comm_impl_AwbSerialPort
 * Method:    sendBytes
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_avrwb_comm_impl_AwbSerialPort_sendBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_avrwb_comm_impl_AwbSerialPort
 * Method:    nativeClose
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_avrwb_comm_impl_AwbSerialPort_nativeClose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
