/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_avrwb_comm_impl_AwbCommDriver */

#ifndef _Included_com_avrwb_comm_impl_AwbCommDriver
#define _Included_com_avrwb_comm_impl_AwbCommDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_avrwb_comm_impl_AwbCommDriver
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_avrwb_comm_impl_AwbCommDriver_nativeInit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_avrwb_comm_impl_AwbCommDriver_InstanceHolder */

#ifndef _Included_com_avrwb_comm_impl_AwbCommDriver_InstanceHolder
#define _Included_com_avrwb_comm_impl_AwbCommDriver_InstanceHolder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
